export const animals = [
    {
        id: 1,
        image: 'panda.jpg',
        species : 'bear',
        furColor: 'white',
        temperament: 'judgemental',
        size: 'hefty',
        price: 7000,
        name: 'Jim',
    },
    {
        id: 2,
        image: 'arcticfox.jpg',
        species : 'fox',
        furColor: 'white',
        temperament: 'playful',
        size: 'medium',
        price: 6500,
        name: 'Gretchen',
    },
    {
        id: 3,
        image: 'capybara.jpg',
        species : 'rodent',
        furColor: 'honeysuckle',
        temperament: 'chill af',
        size: 'medium',
        price: 7500,
        name: 'Gregory',
    },
    {
        id: 4,
        image: 'tiger.jpg',
        species : 'wildcat',
        furColor: 'orange',
        temperament: 'badass',
        size: 'full',
        price: 15000,
        name: 'Hendrix',
    },
    {
        id: 5,
        image: 'lion.jpg',
        species : 'wildcat',
        furColor: 'golden',
        temperament: 'wise',
        size: 'full',
        price: 15000,
        name: 'Huxley'
    },
    {
        id: 6,
        image: 'unicorn.jpg',
        species : 'mythical',
        furColor: 'phosphorescent',
        temperament: 'aloof whimsy',
        size: 'horse',
        price: 34534000,
        name: 'Ezmerelda',
    },
];

